import sourceLandmarks from './landmarks.json';
export type OverlayKind = 'tendinopathy'|'partial'|'rupture'|'stress'|'sprain'|'fluid'|'pressure'|'landmark';
export const overlayColors: Record<OverlayKind,string> = {tendinopathy:'#e5af55',partial:'#f68a47',rupture:'#f45962',stress:'#eb77c8',sprain:'#e5d762',fluid:'#67b9f6',pressure:'#52cbb8',landmark:'#d7bf78'};
export interface Marker {partId:string; position:[number,number,number]; scale:[number,number,number]; kind:OverlayKind;}
export interface Condition {id:string; title:string; shortName:string; region:string; kind:OverlayKind; parts:string[]; mechanism:string; landmark:string; ultrasound:string; mri:string; lookAlikes:string; markers:Marker[]; sources:{title:string;url:string}[]; view:'Posterior'|'Medial'|'Lateral'|'Anterior'|'Foot'|'Sole'; area?:'foot_ankle'|'calf_knee'; landmarkLabel?:string; illustration?:string; transparentParts?:string[];}
const source = {
 achilles:{title:'AAOS · Achilles tendinitis',url:'https://www.orthoinfo.org/diseases--conditions/achilles-tendinitis/'},
 rupture:{title:'AAOS · Achilles tendon rupture',url:'https://www.orthoinfo.org/diseases--conditions/achilles-tendon-rupture-tear/'},
 ankle:{title:'ESSR · Ankle ultrasound guidelines',url:'https://www.essr.org/content-essr/uploads/2016/10/ankle.pdf'},
 tp:{title:'AAOS · Progressive collapsing foot deformity',url:'https://www.orthoinfo.org/diseases--conditions/posterior-tibial-tendon-dysfunction'},
 peroneal:{title:'Melville et al. · US and MRI compared with surgery',url:'https://pubmed.ncbi.nlm.nih.gov/38337434/'},
 tennis:{title:'Delgado et al. · Tennis leg: 141-patient US study',url:'https://pubmed.ncbi.nlm.nih.gov/12091669/'},
 soleus:{title:'Balius et al. · Soleus injury and ultrasound',url:'https://pubmed.ncbi.nlm.nih.gov/24627005/'},
 cecs:{title:'AAOS · Compartment syndrome',url:'https://www.orthoinfo.org/en/diseases--conditions/compartment-syndrome/'},
 sprain:{title:'AAOS · Sprained ankle',url:'https://www.orthoinfo.org/en/diseases--conditions/sprained-ankle'},
 stress:{title:'AAOS · Shin splints',url:'https://www.orthoinfo.org/diseases--conditions/shin-splints/?lv=true'},
 plantar:{title:'AAOS · Plantar fasciitis',url:'https://www.orthoinfo.org/diseases--conditions/plantar-fasciitis-and-bone-spurs'},
 footStress:{title:'AAOS · Foot and ankle stress fractures',url:'https://www.orthoinfo.org/diseases--conditions/stress-fractures-of-the-foot-and-ankle'},
 footImaging:{title:'ACR · Chronic foot pain',url:'https://acsearch.acr.org/docs/69424/Narrative/'},
 ankleImaging:{title:'ACR · Chronic ankle pain',url:'https://acsearch.acr.org/docs/69422/Narrative/'},
 fhl:{title:'Clinical study · Flexor hallucis longus symptoms',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8726539/'},
 fhlDynamic:{title:'Dynamic US / arthroscopy · Hallux saltans (case report)',url:'https://pubmed.ncbi.nlm.nih.gov/29285554/'},
 navicular:{title:'Clinical study · Navicular stress injury and dorsal landmark',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2579456/'},
 talar:{title:'AOFAS · Osteochondral lesion',url:'https://www.footcaremd.org/foot-and-ankle-conditions/ankle/osteochondral-lesion'},
 nerve:{title:'Anatomical report · Common peroneal nerve',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9052142/'}
};
const m=(partId:string,position:Marker['position'],scale:Marker['scale'],kind:OverlayKind):Marker=>({partId,position,scale,kind});
export const conditions:Condition[] = [
 {id:'achilles_mid',title:'Midportion Achilles tendinopathy',shortName:'Achilles · midportion',region:'Posterior ankle',kind:'tendinopathy',parts:['achilles'],view:'Posterior',mechanism:'Repeated tendon loading can produce pain and structural change in the Achilles midportion.',landmark:'Posterior tendon, approximately 2–6 cm proximal to the calcaneal insertion; the amber region is schematic.',ultrasound:'Assesses tendon thickness, fibrillar structure and Doppler signal dynamically.',mri:'Shows tendon structure and the extent of surrounding tissue change; findings need clinical correlation.',lookAlikes:'Insertional tendinopathy, paratenon irritation and partial tear.',markers:[m('achilles',[0,115,-37],[12,22,10],'tendinopathy')],sources:[source.achilles,source.ankle]},
 {id:'achilles_insertion',title:'Insertional Achilles & retrocalcaneal bursa',shortName:'Achilles · insertion',region:'Posterior heel',kind:'tendinopathy',parts:['achilles','calcaneus','retrocalcaneal_bursa'],view:'Posterior',mechanism:'Compression and repeated load may affect the tendon insertion and adjacent bursa; Haglund morphology may coexist.',landmark:'Posterior calcaneal attachment (amber), deep bursa (blue) and posterosuperior calcaneal prominence (amber); these are distinct findings.',ultrasound:'Examines the distal tendon and deep bursal fluid; the bursa lies anterior to Achilles.',mri:'Surveys tendon, bursa and calcaneal marrow; radiographs also show bony morphology.',lookAlikes:'Superficial retro-Achilles bursitis, midportion tendinopathy and inflammatory enthesitis.',markers:[m('achilles',[0,68,-40],[15,11,10],'tendinopathy'),m('retrocalcaneal_bursa',[0,73,-25],[13,7,7],'fluid'),m('calcaneus',[0,67,-18],[15,8,8],'tendinopathy')],sources:[source.achilles,source.ankle]},
 {id:'achilles_rupture',title:'Achilles rupture',shortName:'Achilles rupture',region:'Posterior ankle',kind:'rupture',parts:['achilles'],view:'Posterior',mechanism:'A sudden high tensile load can partially or completely disrupt the Achilles tendon.',landmark:'Example discontinuity above the heel; the red gap symbol does not represent a measured tear.',ultrasound:'Dynamic examination can assess continuity and tendon-end movement; operator expertise matters.',mri:'Can characterize complex tears and associated tissue injury when further detail is needed.',lookAlikes:'Tennis leg, plantaris injury and DVT can also cause calf symptoms; this atlas cannot distinguish or exclude them.',markers:[m('achilles',[0,115,-37],[16,7,13],'rupture')],sources:[source.rupture,source.tennis]},
 {id:'pttd',title:'Tibialis posterior tendinopathy / PTTD',shortName:'Tibialis posterior',region:'Medial ankle',kind:'tendinopathy',parts:['tp_tendon','tibialis_posterior','navicular'],view:'Medial',mechanism:'Repeated loading and degeneration can impair the posterior tibial tendon, sometimes accompanying progressive arch collapse.',landmark:'Tendon behind the medial malleolus, continuing toward the navicular tuberosity.',ultrasound:'Evaluates the tendon and sheath during movement; detects thickening, fluid or discontinuity.',mri:'Surveys the tendon and other medial arch supports; tendon change alone does not prove deformity.',lookAlikes:'Deltoid or spring-ligament pathology, flexor tenosynovitis and medial ankle arthritis.',markers:[m('tp_tendon',[32,96,-9],[10,23,11],'tendinopathy')],sources:[source.tp,source.ankle]},
 {id:'peroneal',title:'Peroneal tendinopathy & brevis split',shortName:'Peroneal tendons',region:'Lateral ankle',kind:'partial',parts:['fl_tendon','fb_tendon'],view:'Lateral',mechanism:'Repeated friction, loading or instability can affect the peroneal tendons and produce a longitudinal brevis split.',landmark:'Behind the lateral malleolus at the retromalleolar groove; orange paired edges indicate a longitudinal split.',ultrasound:'Dynamic US can reveal transient displacement and assess tendon structure.',mri:'Characterizes tears and associated anatomy; neither modality is universally superior.',lookAlikes:'Lateral ligament injury, tendon subluxation and a fifth-metatarsal injury.',markers:[m('fl_tendon',[-42,94,-9],[9,25,9],'tendinopathy'),m('fb_tendon',[-40,94,-2],[6,20,6],'partial')],sources:[source.peroneal,source.ankle]},
 {id:'tennis_leg',title:'Tennis leg · medial gastrocnemius',shortName:'Tennis leg',region:'Posteromedial calf',kind:'partial',parts:['gastrocnemius_medial','plantaris','plantaris_tendon','soleus'],view:'Posterior',mechanism:'Sudden calf loading can injure the medial gastrocnemius near its distal myotendinous junction.',landmark:'Posteromedial calf at the gastrocnemius–soleus interface; the small plantaris is a differential, not the usual injured structure.',ultrasound:'May show superficial fibre disruption and intermuscular fluid; vascular assessment is separate.',mri:'Defines injury extent and can identify deeper or alternative muscle injury.',lookAlikes:'Achilles rupture, soleus or plantaris injury, ruptured Baker cyst and DVT; muscle findings do not exclude DVT.',markers:[m('gastrocnemius_medial',[19,280,-65],[19,27,10],'partial'),m('soleus',[15,265,-56],[19,12,5],'fluid')],sources:[source.tennis]},
 {id:'soleus_strain',title:'Soleus strain',shortName:'Soleus strain',region:'Deep calf',kind:'partial',parts:['soleus'],view:'Posterior',mechanism:'Excess muscle loading can injure soleus fibres, aponeuroses or the central tendon.',landmark:'Soleus lies deep to gastrocnemius; the orange patch is one example site, not a fixed injury location.',ultrasound:'May show accessible fibre disruption but can miss deep soleus injuries.',mri:'Provides a broader assessment of deep muscle and aponeurotic injury.',lookAlikes:'Gastrocnemius injury, Achilles pathology, exertional compartment symptoms and DVT.',markers:[m('soleus',[4,285,-45],[22,33,10],'partial')],sources:[source.soleus,source.tennis]},
 {id:'cecs_anterior',title:'Exertional compartment syndrome · anterior',shortName:'Anterior CECS',region:'Anterior compartment',kind:'pressure',parts:['anterior_compartment','tibialis_anterior'],view:'Anterior',mechanism:'Exertional expansion within a constrained compartment may produce activity-related pain and pressure symptoms.',landmark:'Teal shell represents the anterior compartment lateral to the tibial crest, not an isolated diseased muscle.',ultrasound:'Routine ultrasound does not confirm CECS.',mri:'Exercise-related MRI may contribute in selected settings; assessment may involve compartment-pressure testing.',lookAlikes:'Tibial stress injury, nerve entrapment and vascular causes; acute compartment syndrome is a distinct urgent condition.',markers:[m('anterior_compartment',[-17,287,24],[39,142,32],'pressure')],sources:[source.cecs]},
 {id:'cecs_deep',title:'Exertional compartment syndrome · deep posterior',shortName:'Deep posterior CECS',region:'Deep posterior compartment',kind:'pressure',parts:['deep_posterior_compartment','tibialis_posterior'],view:'Posterior',mechanism:'Exercise-related pressure within the deep posterior compartment may be associated with recurrent calf pain.',landmark:'Teal envelope behind the tibia and interosseous membrane, deep to soleus.',ultrasound:'Routine resting ultrasound cannot establish CECS.',mri:'May help assess alternative causes or exercise-related change; clinical assessment may include pressure testing.',lookAlikes:'MTSS, flexor or tibialis posterior injury and vascular causes; symptoms alone do not confirm CECS.',markers:[m('deep_posterior_compartment',[0,285,-21],[33,143,23],'pressure')],sources:[source.cecs]},
 {id:'lateral_sprain',title:'Lateral ankle sprain · ATFL → CFL',shortName:'Lateral ankle sprain',region:'Lateral ankle',kind:'sprain',parts:['atfl','cfl'],view:'Lateral',mechanism:'Inversion can injure the lateral ligament complex, commonly involving ATFL first and sometimes CFL.',landmark:'ATFL anterior to the lateral malleolus; CFL extends toward the lateral calcaneus below it.',ultrasound:'Can assess superficial ligament fibres dynamically with experienced examination.',mri:'Surveys ligaments, cartilage and associated bone or tendon injuries.',lookAlikes:'Peroneal tendon injury, avulsion fracture and syndesmotic sprain; appearance does not establish stability.',markers:[m('atfl',[-31,83,18],[14,7,12],'sprain'),m('cfl',[-35,59,-3],[8,17,8],'sprain')],sources:[source.sprain,source.ankle]},
 {id:'high_sprain',title:'Syndesmosis sprain',shortName:'Syndesmosis',region:'Distal tibiofibular joint',kind:'sprain',parts:['syndesmosis','tibfib_distal'],view:'Anterior',mechanism:'External rotation and dorsiflexion loading can injure the distal tibiofibular ligament complex.',landmark:'Between distal tibia and fibula just above the ankle mortise.',ultrasound:'Can evaluate accessible anterior ligaments; deeper components and stability have assessment limits.',mri:'Maps ligament and associated bone injury; clinical and other imaging findings inform stability.',lookAlikes:'Lateral ankle sprain, occult fracture and anterior ankle impingement.',markers:[m('syndesmosis',[-20,113,10],[22,12,10],'sprain')],sources:[source.sprain,source.ankle]},
 {id:'mtss',title:'Medial tibial stress syndrome',shortName:'Medial tibial stress',region:'Posteromedial tibial border',kind:'stress',parts:['tibia'],view:'Medial',mechanism:'Repeated loading is associated with exercise-related pain along the posteromedial tibial border.',landmark:'A long magenta region along the distal posteromedial tibia; distribution is schematic.',ultrasound:'Does not reliably exclude bone stress injury.',mri:'Can identify periosteal and marrow stress changes and help assess suspected fracture.',lookAlikes:'Tibial stress fracture, deep posterior CECS and tibialis posterior symptoms; diffuse versus focal pain is not diagnostic.',markers:[m('tibia',[18,203,-8],[7,66,12],'stress')],sources:[source.stress]},
 {id:'stress_fracture',title:'Tibial stress-fracture band',shortName:'Tibial stress fracture',region:'Tibial shaft',kind:'stress',parts:['tibia'],view:'Anterior',mechanism:'Accumulated repetitive loading can exceed bone remodelling capacity and progress to a stress fracture.',landmark:'The focal magenta band is an example location; stress fractures can occur at other tibial sites.',ultrasound:'Cannot reliably exclude a tibial stress fracture.',mri:'Can demonstrate early bone stress change and fracture detail even when early radiographs are unrevealing.',lookAlikes:'MTSS and other causes of focal bone pain; the band is illustrative, not a severity grade.',markers:[m('tibia',[4,226,3],[24,7,21],'stress')],sources:[source.stress]},
 {id:'fibular_neck',title:'Fibular neck · common fibular nerve',shortName:'Fibular neck landmark',region:'Lateral knee',kind:'landmark',parts:['common_fibular_nerve','fibula'],view:'Lateral',mechanism:'The superficial common fibular nerve can be vulnerable to compression or traction around the fibular neck.',landmark:'Nerve winding around the neck just distal to the fibular head; a location marker, not a lesion.',ultrasound:'Can trace accessible nerve anatomy and assess focal structural change.',mri:'Can assess adjacent tissues and denervation patterns; localisation also depends on clinical and electrophysiological assessment.',lookAlikes:'L5 radiculopathy, sciatic neuropathy and more distal fibular nerve lesions.',markers:[m('common_fibular_nerve',[-40,425,-2],[11,17,13],'landmark')],sources:[source.nerve]},

 {id:'plantar_fasciopathy',title:'Plantar fasciitis / fasciopathy',shortName:'Plantar fasciitis',area:'foot_ankle',region:'Plantar heel',kind:'tendinopathy',parts:['plantar_aponeurosis','calcaneus'],view:'Sole',mechanism:'Repeated loading can irritate and damage the proximal plantar fascia at its attachment beneath the heel.',landmark:'Plantar-medial calcaneal attachment, underneath the heel. First-step pain after rest is common but not diagnostic; this differs from the Achilles attachment behind the heel.',ultrasound:'When imaging is indicated, US assesses fascial thickness, fibre structure and tears; this condition is often assessed clinically.',mri:'Shows fascia, surrounding tissue and alternative bone pathology when further assessment is needed.',lookAlikes:'Calcaneal stress injury, heel fat-pad pain, nerve entrapment and insertional Achilles disease. A heel spur is not required and does not establish the cause of pain.',illustration:'Amber marks an example proximal fascial region, not a measured lesion. The source sheet lacks detailed distal digital branches.',markers:[m('plantar_aponeurosis',[8,16,-30],[9,5,13],'tendinopathy')],sources:[source.plantar,source.footImaging]},
 {id:'fhl_tenosynovitis',title:'Flexor hallucis longus tenosynovitis',shortName:'FHL tendon sheath',area:'foot_ankle',region:'Deep posterior ankle',kind:'fluid',parts:['fhl_tendon','fhl_sheath','talus','calcaneus'],view:'Medial',landmarkLabel:'Deep anatomical landmark',mechanism:'Repeated tendon excursion or friction can irritate the sheath around flexor hallucis longus as it passes through the posterior ankle.',landmark:'Behind the talus and deep to the medial ankle, continuing beneath the sustentaculum tali towards the great toe. This is a deep course, not a precise surface self-palpation target.',ultrasound:'Dynamic US can assess accessible tendon glide, sheath changes and snapping; sheath fluid alone does not establish symptomatic tenosynovitis.',mri:'Assesses the deep tendon course and associated ankle abnormalities; imaging findings require clinical correlation.',lookAlikes:'Tibialis posterior or FDL tendon disease, posterior ankle impingement and Achilles pathology; more distal symptoms may overlap plantar fascia pain.',illustration:'Blue indicates example sheath fluid, not the full extent of disease. No os trigonum variant is represented.',markers:[m('fhl_sheath',[10,68,-24],[6,12,6],'fluid')],sources:[source.fhl,source.fhlDynamic,source.ankleImaging]},
 {id:'navicular_stress',title:'Navicular bone stress injury',shortName:'Navicular stress injury',area:'foot_ankle',region:'Dorsal midfoot',kind:'stress',parts:['navicular'],view:'Foot',mechanism:'Repetitive loading can produce a stress response or fracture in the navicular.',landmark:'Proximal dorsal central navicular, often called the N spot; distinct from the medial tuberosity where tibialis posterior inserts. Tenderness alone is not diagnostic.',ultrasound:'Cannot exclude an internal bone stress injury.',mri:'Shows marrow stress response and occult injury; CT can define a fracture line. Early radiographs may be unrevealing.',lookAlikes:'Tibialis posterior insertion pain, midfoot joint disease and other midfoot injuries.',illustration:'The magenta region indicates an example site, not a fracture line or severity grade.',markers:[m('navicular',[0,75,29],[7,5,6],'stress')],sources:[source.navicular,source.footStress,source.footImaging]},
 {id:'metatarsal_stress',title:'Metatarsal bone stress injury',shortName:'Metatarsal stress injury',area:'foot_ankle',region:'Forefoot',kind:'stress',parts:['metatarsal_2','metatarsal_3'],view:'Foot',mechanism:'Repetitive forefoot loading can exceed a metatarsal’s capacity to remodel.',landmark:'Second-metatarsal shaft example on the dorsal forefoot; other metatarsals, including the third, may also be affected.',ultrasound:'May assess superficial abnormalities but does not reliably exclude bone stress injury.',mri:'Detects occult stress changes when initial radiographs are negative; findings are interpreted with symptoms and examination.',lookAlikes:'Extensor tendon irritation, metatarsophalangeal or plantar-plate pathology and acute fracture.',illustration:'A focal magenta patch locates an illustrative shaft injury; it is not a complete fracture band.',markers:[m('metatarsal_2',[-15,50,86],[6,6,12],'stress')],sources:[source.footStress,source.footImaging]},
 {id:'calcaneal_stress',transparentParts:['calcaneus'],title:'Calcaneal bone stress injury',shortName:'Calcaneal stress injury',area:'foot_ankle',region:'Heel bone',kind:'stress',parts:['calcaneus'],view:'Lateral',landmarkLabel:'Bone region and surface context',mechanism:'Repeated impact loading can cause stress injury within the calcaneus.',landmark:'Calcaneal body beneath and anterior to the Achilles attachment. This internal bone region differs from the plantar fascia attachment underneath the heel.',ultrasound:'Cannot assess the full marrow or reliably exclude a calcaneal stress injury.',mri:'Can identify bone stress injury when heel symptoms overlap with plantar fasciitis and radiographs are unrevealing.',lookAlikes:'Plantar fasciopathy, heel-pad pain and Achilles insertion pathology; location alone does not distinguish them.',illustration:'Magenta locates an example internal stress region. The translucent bone reveals its position; no fracture line is asserted.',markers:[m('calcaneus',[-5,32,-32],[13,12,13],'stress')],sources:[source.footStress,source.footImaging]},
 {id:'talar_osteochondral',title:'Osteochondral lesion of the talus',shortName:'Talar-dome lesion',area:'foot_ankle',region:'Ankle joint · talar dome',kind:'stress',parts:['talus','talocrural'],view:'Foot',landmarkLabel:'Deep joint landmark',mechanism:'An ankle injury or repeated trauma can damage talar-dome cartilage and its underlying bone.',landmark:'Example site on the superior talar dome beneath the tibial plafond; it is deep inside the ankle and cannot be directly palpated.',ultrasound:'Is not routinely used to assess talar osteochondral lesions because access to the articular surface is limited.',mri:'Assesses cartilage, underlying bone and associated abnormalities; CT provides additional bony detail.',lookAlikes:'Persistent ligament injury or instability, impingement, synovitis, arthritis and tendon pathology.',illustration:'Magenta marks a schematic cartilage–bone site, not a graded defect. Lesions can occur elsewhere on the dome; surrounding structures fade to expose this deep location.',markers:[m('talus',[10,85,-7],[8,4,8],'stress')],sources:[source.talar,source.ankleImaging]}

];
for(const condition of conditions){
 condition.area??=['tennis_leg','soleus_strain','cecs_anterior','cecs_deep','mtss','stress_fracture','fibular_neck'].includes(condition.id)?'calf_knee':'foot_ankle';
 const markers=sourceLandmarks[condition.id as keyof typeof sourceLandmarks];
 if(!markers)throw new Error(`Missing source landmarks: ${condition.id}`);
 condition.markers=markers.map(marker=>{
  if(marker.position.length!==3||marker.scale.length!==3||!Object.hasOwn(overlayColors,marker.kind))throw new Error(`Invalid source landmark: ${condition.id}`);
  return {...marker,position:marker.position as Marker['position'],scale:marker.scale as Marker['scale'],kind:marker.kind as OverlayKind};
 });
}
